project:
  title: "My Research Project"
  type: default
  output-dir: outputs
  # opcional: renderizar só arquivos .qmd da raiz
  # render:
  #   - "*.qmd"

author:
  - name: "**Gustavo Santos Paiva Laender Moura**"
    affiliation: "University of São Paulo, Ribeirão Preto Medical School, Department of Internal Medicine"
    email: "gsplmoura@usp.br"

site: "https://github.com/gsplmoura"
date: today

# Execução (R/knitr)
execute:
  eval: true
  echo: true
  output: true
  cache: true
  # cache-dir: outputs   # <- vale para Jupyter; para R/knitr use knitr.opts_chunk.cache.path
  # warning: false
  # message: false
  # error: false
  # freeze: auto
  dpi: 300
  fig-format: png

# knitr (R)
knitr:
  opts_chunk:
    dev: "png"
    fig.align: "center"
    fig.width: 6
    fig.height: 4
    cache: true
    cache.path: "outputs/.knitr-cache/"   # <- cache do knitr vai para outputs
    fig.path: "outputs/figs/" # opcional: mandar figuras para uma pasta dentro de outputs

# Formatos de saída
format:
  html:
    theme: flatly
    toc: true
    toc-depth: 5
    toc-location: left
    number-sections: true
    highlight-style: github
    code-fold: false
    smooth-scroll: true
    citations-hover: true
    reference-location: margin
    self-contained: true

  pdf:
    documentclass: article
    toc: true
    toc-depth: 4
    number-sections: true
    keep-tex: true
    fig-pos: "H"

  docx:
    #reference-doc: "template.docx"
    #number-sections: true
    toc: true

  markdown:
    variant: gfm
    preserve-yaml: true

# Idioma
lang: en
lang-title: "Title"
lang-abstract: "Abstract"

# Referências
bibliography:
  - Library/BibTeX/article.bib
  - Library/BibTeX/book.bib
  - Library/BibTeX/booklet.bib
  - Library/BibTeX/conference.bib
  - Library/BibTeX/inbook.bib
  - Library/BibTeX/incollection.bib
  - Library/BibTeX/inproceedings.bib
  - Library/BibTeX/manual.bib
  - Library/BibTeX/mastersthesis.bib
  - Library/BibTeX/misc.bib
  - Library/BibTeX/phdthesis.bib
  - Library/BibTeX/proceedings.bib
  - Library/BibTeX/techreport.bib
  - Library/BibTeX/unpublished.bib

# csl: apa.csl
link-citations: true
link-bibliography: true

# Cross-referencing
crossref:
  fig-prefix: "Figure"
  tbl-prefix: "Table"
  eq-prefix: "Equation"

# Licença
license: "CC BY 4.0"

# Parâmetros customizados
params:
  data_source: "dataset.csv"
  analysis_type: "regression"