{
  "hash": "3ca06554c143010e7ed96368df483285",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"Wrangling\"\nformat: html\n---\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nlibrary(tidyverse)\nlibrary(readxl)\nlibrary(janitor)\nlibrary(here)\nlibrary(skimr)\nlibrary(lubridate)\n```\n:::\n\n\n\n# Patients\n\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\npatients <- read_delim(here(\"data\",\"Levantamento_GLPI_58686_Sol_123_2023_Pacientes.csv\"), delim = \";\") %>% \n  janitor::clean_names() %>%\n  mutate(\n    birthdate = dmy(dta_nascimento),\n    race = as.factor(raca_etnia),\n    sex = as.factor(idf_sexo),\n    death_date = dmy(dta_obito),\n    date = dmy(dta_hor_consulta)\n  ) %>%\n  arrange(desc(death_date)) %>%\n  select(\n    record_id = registro,\n    birthdate,\n    race,\n    sex,\n    death_date\n  ) %>% \n  distinct(record_id, .keep_all = TRUE)\n\nskimr::skim(patients)\n```\n\n::: {.cell-output-display}\n\nTable: Data summary\n\n|                         |         |\n|:------------------------|:--------|\n|Name                     |patients |\n|Number of rows           |872      |\n|Number of columns        |5        |\n|_______________________  |         |\n|Column type frequency:   |         |\n|character                |1        |\n|Date                     |2        |\n|factor                   |2        |\n|________________________ |         |\n|Group variables          |None     |\n\n\n**Variable type: character**\n\n|skim_variable | n_missing| complete_rate| min| max| empty| n_unique| whitespace|\n|:-------------|---------:|-------------:|---:|---:|-----:|--------:|----------:|\n|record_id     |         0|             1|   8|   8|     0|      872|          0|\n\n\n**Variable type: Date**\n\n|skim_variable | n_missing| complete_rate|min        |max        |median     | n_unique|\n|:-------------|---------:|-------------:|:----------|:----------|:----------|--------:|\n|birthdate     |         0|           1.0|1927-01-18 |2014-11-30 |1975-01-29 |      852|\n|death_date    |       785|           0.1|2016-04-03 |2023-12-04 |2021-04-06 |       86|\n\n\n**Variable type: factor**\n\n|skim_variable | n_missing| complete_rate|ordered | n_unique|top_counts                          |\n|:-------------|---------:|-------------:|:-------|--------:|:-----------------------------------|\n|race          |         0|             1|FALSE   |        5|Bra: 664, Mul: 129, Pre: 72, VER: 5 |\n|sex           |         0|             1|FALSE   |        2|F: 553, M: 319                      |\n\n\n:::\n:::\n\n\n\nThe patients dataset consists of *872 unique participants* and 5 variables, encompassing patient identifiers, demographic characteristics, and dates of birth and death. The `record_id` variable (character) serves as a unique identifier, with all values having a fixed length of 8 characters and no missing data. The dataset includes two date variables: `birthdate`, which is fully complete and ranges from January 18, 1927, to November 30, 2014, with a median birthdate of January 29, 1975; and `death_date`, which has *785 missing values (89.9%)*, indicating that most participants are still alive. The `race` variable (factor) has 5 categories, with the most common being “Branco” (white, 664 participants), followed by “Pardo” (mixed-race, 129 participants) and “Preto” (Black, 72 participants). The `sex` variable (factor) has two categories, with 553 females (63.4%) and 319 males (36.6%). The dataset is well-structured, with complete demographic information and some missing data in the mortality records.\n\n# Consultations\n\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nconsultas <- read_delim(here(\"data\",\"Levantamento_GLPI_58686_Sol_123_2023_Pacientes.csv\"), delim = \";\") %>% \n  janitor::clean_names() %>%\n  mutate(\n    date = dmy(dta_hor_consulta),\n  ) %>%\n  select(\n    record_id = registro,\n    date) %>% \n  mutate(\n    age = as.numeric( # Converts duration object to numeric value\n      (date - patients$birthdate) / dyears(1) # dyears(1) from lubridate: represents the duration of one year (365.25 days), ensuring leap years are accounted for.\n      )\n    )\n\nskimr::skim(consultas)\n```\n\n::: {.cell-output-display}\n\nTable: Data summary\n\n|                         |          |\n|:------------------------|:---------|\n|Name                     |consultas |\n|Number of rows           |5212      |\n|Number of columns        |3         |\n|_______________________  |          |\n|Column type frequency:   |          |\n|character                |1         |\n|Date                     |1         |\n|numeric                  |1         |\n|________________________ |          |\n|Group variables          |None      |\n\n\n**Variable type: character**\n\n|skim_variable | n_missing| complete_rate| min| max| empty| n_unique| whitespace|\n|:-------------|---------:|-------------:|---:|---:|-----:|--------:|----------:|\n|record_id     |         0|             1|   8|   8|     0|      872|          0|\n\n\n**Variable type: Date**\n\n|skim_variable | n_missing| complete_rate|min        |max        |median     | n_unique|\n|:-------------|---------:|-------------:|:----------|:----------|:----------|--------:|\n|date          |         0|             1|2016-01-19 |2023-10-24 |2019-05-14 |      367|\n\n\n**Variable type: numeric**\n\n|skim_variable | n_missing| complete_rate|  mean|    sd|   p0|   p25|   p50|   p75|  p100|hist  |\n|:-------------|---------:|-------------:|-----:|-----:|----:|-----:|-----:|-----:|-----:|:-----|\n|age           |         0|             1| 45.26| 15.18| 1.54| 34.63| 44.59| 56.11| 95.86|▁▆▇▃▁ |\n\n\n:::\n:::\n\n\n\nThe consultas dataset contains 5,212 observations across 2 variables, representing multiple consultation records for 872 unique participants. The record_id variable (character) serves as a unique identifier for each patient, with all values having a fixed length of 8 characters and no missing data. The date variable (Date) captures the consultation dates, spanning from January 19, 2016, to October 24, 2023, with 367 unique dates. The dataset is fully complete, with no missing values, and provides a structured timeline of patient consultations.\n\n## Age at consultation\n\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nunderage <- consultas %>% \n    filter( age < 18\n    ) %>% \n  distinct(record_id, .keep_all = TRUE)\n\nsum(consultas$age < 18)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 168\n```\n\n\n:::\n\n```{.r .cell-code}\nadults <- consultas %>% \n    filter( age >= 18\n    ) %>% \n  distinct(record_id, .keep_all = TRUE)\n\ncommon_record_ids <- intersect(underage$record_id, adults$record_id)\n```\n:::\n\n\n\nA total of 146 patients were seen in the clinic while underage, accounting for 168 consultations. Of these, 138 continued follow-up after reaching adulthood, leaving only 8 patients who remained underage throughout the entire follow-up period.\n\n# Anthropometric measures\n\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nmonitorizacao <- read_excel(here(\"data\",\"Levantamento_GLPI_58686_Sol_123_2023_Monitorizacao_Isabela.xlsx\"), sheet = 1) %>% \n  select(\n    record_id, type, date, value\n  )\n\nweight <- monitorizacao %>% \n  filter(\n    type == \"weight_kg\"\n  ) %>% \n  select(\n    record_id, date, value\n  ) %>% \n  rename(\n    weight_kg = value\n  )\n\nalturas_faltantes <- read_excel(here(\"data\",\"alturas_faltantes.xlsx\")) %>% janitor::clean_names() %>% \n  filter(\n    !is.na(altura_metros_ponto_como_separador_decimal)\n  ) %>% \n  select(\n    record_id = registro,\n    height_m = altura_metros_ponto_como_separador_decimal\n    ) %>% \n  mutate(\n    date = as.POSIXct(NA)\n    )\n\nheight <- monitorizacao %>% \n  filter(\n    type == \"height_m\"\n    ) %>% \n  select(\n    record_id, date, value\n  ) %>% \n  rename(\n    height_m = value\n  ) %>% \n  rbind(., alturas_faltantes) %>% \n  mutate(\n    height_m = as.numeric(height_m)\n  )\n\nrm(monitorizacao)\nrm(alturas_faltantes)\n```\n:::\n\n\n\n## Height\n\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nskimr::skim(height)\n```\n\n::: {.cell-output-display}\n\nTable: Data summary\n\n|                         |       |\n|:------------------------|:------|\n|Name                     |height |\n|Number of rows           |5066   |\n|Number of columns        |3      |\n|_______________________  |       |\n|Column type frequency:   |       |\n|character                |1      |\n|numeric                  |1      |\n|POSIXct                  |1      |\n|________________________ |       |\n|Group variables          |None   |\n\n\n**Variable type: character**\n\n|skim_variable | n_missing| complete_rate| min| max| empty| n_unique| whitespace|\n|:-------------|---------:|-------------:|---:|---:|-----:|--------:|----------:|\n|record_id     |         0|             1|   8|   8|     0|      856|          0|\n\n\n**Variable type: numeric**\n\n|skim_variable | n_missing| complete_rate| mean|   sd|  p0|  p25|  p50|  p75| p100|hist  |\n|:-------------|---------:|-------------:|----:|----:|---:|----:|----:|----:|----:|:-----|\n|height_m      |         0|             1| 1.64| 0.12| 0.2| 1.56| 1.65| 1.72| 1.96|▁▁▁▅▇ |\n\n\n**Variable type: POSIXct**\n\n|skim_variable | n_missing| complete_rate|min        |max        |median     | n_unique|\n|:-------------|---------:|-------------:|:----------|:----------|:----------|--------:|\n|date          |        76|          0.98|2016-01-21 |2023-10-26 |2019-02-05 |     1355|\n\n\n:::\n\n```{.r .cell-code}\nggplot(height, aes(height_m)) + geom_histogram()\n```\n\n::: {.cell-output-display}\n![](Wrangling_files/figure-html/unnamed-chunk-6-1.png){fig-align='center'}\n:::\n:::\n\n\n\nThe height dataset contains **5,066 observations** across **3 variables**, representing repeated height measurements for **856 unique participants** over time. The `record_id` variable (character) serves as a unique identifier for each participant. The `height_m` variable (numeric) records height in meters, with values ranging from **0.2 to 1.96 meters**, a mean of **1.64 meters**, and a standard deviation of **0.121**. No missing values are present in this column. The `date` variable (POSIXct) captures the measurement date, spanning from **January 21, 2016, to October 26, 2023**, with **1,355 unique dates**. The dataset is complete, except for **76 missing values in the date column**, resulting in a **98.5% completeness rate** for dates. These missing values correspond to height measurements that were **not originally included in the dataset exported by the hospital’s data center** but were **manually collected from records**.\n\n### Grouping by record_id\n\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nheight_summarise <- height %>% \n  group_by(record_id) %>% \n  summarise(\n    count_age = n(),\n    mean_age = mean(height_m, na.rm = TRUE),\n    stdev_age = stats::sd(height_m, na.rm = TRUE)\n  ) %>% \n      ungroup()\n```\n:::\n\n\n\n\n## Weight\n\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nskimr::skim(weight)\n```\n\n::: {.cell-output-display}\n\nTable: Data summary\n\n|                         |       |\n|:------------------------|:------|\n|Name                     |weight |\n|Number of rows           |15792  |\n|Number of columns        |3      |\n|_______________________  |       |\n|Column type frequency:   |       |\n|character                |1      |\n|numeric                  |1      |\n|POSIXct                  |1      |\n|________________________ |       |\n|Group variables          |None   |\n\n\n**Variable type: character**\n\n|skim_variable | n_missing| complete_rate| min| max| empty| n_unique| whitespace|\n|:-------------|---------:|-------------:|---:|---:|-----:|--------:|----------:|\n|record_id     |         0|             1|   8|   8|     0|      862|          0|\n\n\n**Variable type: numeric**\n\n|skim_variable | n_missing| complete_rate|  mean|    sd| p0| p25| p50|   p75| p100|hist  |\n|:-------------|---------:|-------------:|-----:|-----:|--:|---:|---:|-----:|----:|:-----|\n|weight_kg     |         0|             1| 112.1| 40.27|  6|  82| 108| 139.5|  300|▂▇▅▁▁ |\n\n\n**Variable type: POSIXct**\n\n|skim_variable | n_missing| complete_rate|min        |max        |median     | n_unique|\n|:-------------|---------:|-------------:|:----------|:----------|:----------|--------:|\n|date          |         0|             1|2016-01-19 |2023-10-26 |2019-03-27 |     2053|\n\n\n:::\n\n```{.r .cell-code}\nggplot(weight, aes(weight_kg)) + geom_histogram()\n```\n\n::: {.cell-output-display}\n![](Wrangling_files/figure-html/unnamed-chunk-8-1.png){fig-align='center'}\n:::\n:::\n\n\n\nThe weight dataset contains **15,792 observations** across **3 variables**, representing repeated weight measurements for **862 unique participants** over time. The record_id variable (character) uniquely identifies each participant. The weight_kg variable (numeric) captures weight in kilograms, ranging from **6 to 300 kg**, with a mean of **112 kg** and a standard deviation of **40.3 kg**. No missing values are present in this column. The date variable (POSIXct) records the measurement date, spanning from **January 19, 2016, to October 26, 2023**, with **2,053 unique dates**. The dataset is complete, with no missing values in any column.\n\n# Joining consultations, height and weight\n\nIssue:\n\nI want to create a new df based on `consultas` such that this new df will have 2 additional columns, `height_m` and `weight_kg`. Naturally, `height_m` and `weight_kg` should be matched by record_id. However, this is a longitudinal database, so `record_id` might appear multiple times in the spreadsheets.\n\nIdeally, the new df shoudl have the `height_m` and `weight_kg` that matches the record_id as well as the `date`. However, some rows from consultas might not have exact date matches for `height_m` and `weight_kg`. In that case, the new df should match `height_m` and `weight_kg` by the date closest to the actual date of the consultation. \n\nThere are several solutions to this problem: using `fuzzyjoin`, `data.table`, or `purr`. If you’re looking for the simplest approach, fuzzyjoin is the easiest to learn as it closely follows dplyr syntax and allows fuzzy matching with minimal effort. If speed and efficiency are your priority, especially with large datasets, data.table is the fastest, using optimized rolling joins (roll = \"nearest\") but has a steeper learning curve. For a pure Tidyverse solution, purrr offers the most flexibility but requires complex row-wise operations and is harder to master.\n\n## Height\n\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nlibrary(fuzzyjoin)\n\n# Perform the fuzzy join on record_id\nfuzzy_height <- fuzzy_left_join(\n  consultas, height,\n  by = c(\"record_id\" = \"record_id\"),\n  match_fun = list(`==`)\n)\n\n# Checking the column names in joined_df: you'll see \"record_id.x\" from consultas and \"record_id.y\" from height.\n\n# Compute the absolute date difference using the consultation date (date.x) and the height date (date.y)\nfuzzy_height <- fuzzy_height %>% \n  mutate(date_diff = abs(as.numeric(difftime(date.x, date.y, units = \"days\"))))\n\n# For each consultation (identified by record_id.x and the consultation date date.x), select the row with the minimum date difference.\nconsultas_new <- fuzzy_height %>% \n  group_by(record_id.x, date.x) %>% \n  slice_min(order_by = date_diff, with_ties = FALSE) %>% \n  ungroup() %>%\n  # Rename columns for clarity\n  rename(record_id = record_id.x,\n         consult_date = date.x,\n         height_date = date.y,\n         date_diff_height = date_diff) %>% \n  select(\n    record_id, consult_date, age, height_m, date_diff_height\n  )\n```\n:::\n\n\n\n## Weight\n\nWe'll follow a similar process to the height join. The idea is to perform a fuzzy join on `record_id`, calculate the absolute difference between the consultation date (already stored as `consult_date` in `consultas_new` and the weight measurement date (stored in weight's date, then for each consultation choose the weight record with the minimum difference.\n\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\n# Perform the fuzzy join on record_id for weight\nfuzzy_weight <- fuzzy_left_join(\n  consultas_new, weight,\n  by = c(\"record_id\" = \"record_id\"),\n  match_fun = list(`==`)\n)\n\n# Compute the absolute date difference using the consultation date (consult_date) and the weight measurement date (date from weight)\nfuzzy_weight <- fuzzy_weight %>% \n  mutate(date_diff = abs(as.numeric(difftime(consult_date, date, units = \"days\"))))\n\n# For each consultation (identified by record_id.x and consult_date), select the row with the minimum date difference\n\nconsultas_final <- fuzzy_weight %>% \n  group_by(record_id.x, consult_date) %>% \n  slice_min(order_by = date_diff, with_ties = FALSE) %>% \n  ungroup() %>%\n  # Rename columns for clarity\n  rename(record_id = record_id.x,\n         weight_date = date,\n         date_diff_weight = date_diff) %>%\n  mutate(\n    bmi = weight_kg / (height_m * height_m)\n  ) %>% \n  select(record_id, consult_date, age, height_m, date_diff_height, weight_kg, weight_date, date_diff_weight, bmi)\n```\n:::\n",
    "supporting": [],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}